#!/usr/bin/env bash

cat << EOF > environment
############
# Secrets
# YOU MUST CHANGE THESE BEFORE GOING INTO PRODUCTION
############
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
JWT_SECRET=$JWT_SECRET
ANON_KEY=$ANON_KEY
SERVICE_ROLE_KEY=$SERVICE_ROLE_KEY
DASHBOARD_USERNAME=$DASHBOARD_USERNAME
DASHBOARD_PASSWORD=$DASHBOARD_PASSWORD

############
# Database - You can change these to any PostgreSQL database that has logical replication enabled.
############
POSTGRES_HOST=$POSTGRES_HOST
POSTGRES_DB=$POSTGRES_DB
POSTGRES_PORT=$POSTGRES_PORT
# default user is postgres

############
# API Proxy - Configuration for the Kong Reverse proxy.
############
KONG_HTTP_PORT=$KONG_HTTP_PORT
KONG_HTTPS_PORT=$KONG_HTTPS_PORT

############
# API - Configuration for PostgREST.
############
PGRST_DB_SCHEMAS=$PGRST_DB_SCHEMAS

############
# Auth - Configuration for the GoTrue authentication server.
############
## General
SITE_URL=$SITE_URL
ADDITIONAL_REDIRECT_URLS=$ADDITIONAL_REDIRECT_URLS
JWT_EXPIRY=$JWT_EXPIRY
DISABLE_SIGNUP=$DISABLE_SIGNUP
API_EXTERNAL_URL=$API_EXTERNAL_URL
## Mailer Config
MAILER_URLPATHS_CONFIRMATION=$MAILER_URLPATHS_CONFIRMATION
MAILER_URLPATHS_INVITE=$MAILER_URLPATHS_INVITE
MAILER_URLPATHS_RECOVERY=$MAILER_URLPATHS_RECOVERY
MAILER_URLPATHS_EMAIL_CHANGE=$MAILER_URLPATHS_EMAIL_CHANGE
## Email auth
ENABLE_EMAIL_SIGNUP=$ENABLE_EMAIL_SIGNUP
ENABLE_EMAIL_AUTOCONFIRM=$ENABLE_EMAIL_AUTOCONFIRM
SMTP_ADMIN_EMAIL=$SMTP_ADMIN_EMAIL
SMTP_HOST=$SMTP_HOST
SMTP_PORT=$SMTP_PORT
SMTP_USER=$SMTP_USER
SMTP_PASS=$SMTP_PASS
SMTP_SENDER_NAME=$SMTP_SENDER_NAME
## Phone auth
ENABLE_PHONE_SIGNUP=$ENABLE_PHONE_SIGNUP
ENABLE_PHONE_AUTOCONFIRM=$ENABLE_PHONE_AUTOCONFIRM

############
# Studio - Configuration for the Dashboard
############
STUDIO_DEFAULT_ORGANIZATION=$STUDIO_DEFAULT_ORGANIZATION
STUDIO_DEFAULT_PROJECT=$STUDIO_DEFAULT_PROJECT
STUDIO_PORT=$STUDIO_PORT
# replace if you intend to use Studio outside of localhost
SUPABASE_PUBLIC_URL=$SUPABASE_PUBLIC_URL
# Enable webp support
IMGPROXY_ENABLE_WEBP_DETECTION=$IMGPROXY_ENABLE_WEBP_DETECTION

############
# Functions - Configuration for Functions
############
# NOTE: VERIFY_JWT applies to all functions. Per-function VERIFY_JWT is not supported yet.
FUNCTIONS_VERIFY_JWT=$FUNCTIONS_VERIFY_JWT

############
# Logs - Configuration for Logflare
# Please refer to https://supabase.com/docs/reference/self-hosting-analytics/introduction
############
LOGFLARE_LOGGER_BACKEND_API_KEY=$LOGFLARE_LOGGER_BACKEND_API_KEY
# Change vector.toml sinks to reflect this change
LOGFLARE_API_KEY=$LOGFLARE_API_KEY
# Docker socket location - this value will differ depending on your OS
DOCKER_SOCKET_LOCATION=$DOCKER_SOCKET_LOCATION
# Google Cloud Project details
GOOGLE_PROJECT_ID=$GOOGLE_PROJECT_ID
GOOGLE_PROJECT_NUMBER=$GOOGLE_PROJECT_NUMBER

# ZACH added
POSTGREST_PORT=$POSTGREST_PORT
EOF
